### PR TITLE
Fixing API change in pixell 0.19.0

### PR DESCRIPTION
**Pull request by xgarrido**
pixell is broken with the latest version of pillow (see https://github.com/simonsobs/pspy/pull/65#issuecomment-1628739436)

### CODE REVIEW

**Comment by xzackli** [comment]
@xgarrido should we bound pixell versions to < 0.18?

**Comment by xgarrido** [comment]
Actually this branch is for trying to use `pixell` latest version 0.19.0 and thus fix the unit tests. There is a small change in the `pixell` API but the tests remains broken.

**Comment by xgarrido** [comment]
@xzackli in the current `master` branch we now downgrade `pixell` to fix the unit test. We will work on new `pixell` version later

**Comment by xgarrido** [comment]
Here is a summary just to not to forget what have been done:
- the current `pixell` version 0.19.2 has fixed different bugs that makes the unit test on `ubuntu` passing without problem (and with no changes or no new generation of reference data)
- on mac os, the issue is not the tests by themself but the way `ducc` is installed. The error is how the threads are used and I haven't found a way (compile `ducc` from sources for instance) or an option (see https://gitlab.mpcdf.mpg.de/mtr/ducc/-/blob/ducc0/setup.py#L22) to make it working.

**Comment by xgarrido** [comment]
Unit tests are all passing on linux as well as on mac. When using different C++ compilers namely `gcc` vs. `clang` it raises an error due to the conversion of `OMP_NUM_THREADS` env. variable into `long int` by `ducc`. Basically this [line](https://github.com/simonsobs/pixell/blob/master/pixell/curvedsky.py#L10C49-L10C64) in `pixell` set the `DUCC0_NUM_THREADS` variable to `OMP_NUM_THREADS` and, in case the `OMP_NUM_THREADS` is not set the `utils.getenv` of `pixell` sets the value to `None`. When `ducc` converts the string `None` into `long int` via this function https://gitlab.mpcdf.mpg.de/mtr/ducc/-/blob/ducc0/src/ducc0/infra/threading.cc#L108 it's actually impossible : with GNU compiler on linux, no error is raised and actually the value returned by `mystrtol` is zero but with `clang`, it raises an error. 

Within our unit test, we set the `OMP_NUM_THREADS` to zero but I think `pixell` should set the default returned value from `utils.getenv` to zero something like
```python
utils.setenv("DUCC0_NUM_THREADS", utils.getenv("OMP_NUM_THREADS", 0), keep=True)
```

**Comment by amaurea** [comment]
This should be fixed in pixell 0.20.3

**Comment by xgarrido** [comment]
@thibautlouis I think we are good to go and to move `pspy` to `pixell 0.20.3` and `ducc`. We will update `numpy` when the `f2py` bug will be fixed (next release 1.26.1 I guess, see https://github.com/simonsobs/pspy/pull/78#issuecomment-1746292419)

**Comment by xgarrido** [comment]
As expected `numpy 1.26.1` fixes the issues with `fortran` compilation. There is no more stopper.

**Pull request merged**
